AugurProject/augur.js

src/modules/compositeGetters.js

https://app.clubhouse.io/augur/story/594/fix-cache-node-fallback
This change simply empties the `augurNodes.nodes` array if there is an error connecting to a cache node. This will stop the code from retrying the cache node since it doesn't have any to check for anymore and fall back to the hosted node connection to load markets in chunks as expected.

594 fix cache node fallback

---

test/unit/core/filters.js

fixed an issue with the build breaking due to a test of filters.pacemaker. This is due to the way node handles setInterval. in node 7 the function that gets called was moved from _repeat to _onTimeout. we placed a conditional in the test to properly assert a test.

Fixed issue with unit tests

---

src/modules/compositeGetters.js

This is not currently supported by ethrpc and because it is on the transaction it breaks when communicating with ethereum nodes that are strict about the payloads they receive (e.g., Parity).

Removes timeout from `getMarketInfo`.

---

src/chat.js
src/index.js
src/modules/compositeGetters.js
src/modules/logs.js
test/unit/core/logs.js

Fixes duplicate ethrpc inclusion:  ethrpc needs to come from `ethereumjs-connect`, otherwise you end up using/mutating a copy that is never connected and should never be used.
Removes timeout from getLogs object:  This is not used by ethrpc, and it is not cleared by ethrpc because it is on a nested object rather than the params array directly, and it causes problems in Parity since Parity doesn't like extraneous parameters.  Same fix as a previous issue with `timeout` being added to a sub-object.
Fixes a bug where the last chunk of markets wouldn't load:  `startIndex` for the last chunk worth of markets will always be 0.  If sort is descending, this will result in `numMarketsToLoad` being set to `0` which terminates the load prematurely.

Bugfixes found while trying to get Augur working with Parity PoA chain

---

src/modules/compositeGetters.js
test/unit/core/compositeGetters.js

Also adds an assertion in the code.
Note that these tests weren't actually testing the "only non-zero volume" logic previously (that logic is in the contracts), so I renamed them to be more clear about that.  I also removed a test that differed only by that, since it was a redundant test.

Fixes some tests.

---

src/events/get-all-augur-logs.js

There's a lot that could go wrong in parseLog, so let's catch a really common error outside of that loop so we don't confuse where the issue is happening.
This gives an explanatory message when an event is found on a contract for which we do not have a signature mapping entry for. Looks like:
`
Contract Augur has no event signature 0x6eb56ff6339181597ed10da7672cd3c735551d93d152bd072fa389317f3a0149, found on tx 0xe4fefc44a289eaa733efade195b2e1fba68c18b5afea0cdf1a082f103e86f8f9
`

simple warning when abi does not match parsed log

---

src/augur-node/subscribe-to-event.js

`params` is not being used anywhere on the backend, so Paul and I figured it would be best to remove it for the time being.

Removing params parameter from subscribeToEvent

---

index.d.ts

I'm defining this here because augur-contracts is going away. Technically, it should be a type in augur-contracts we re-export.

add type for uploadBlockNumbers

---

src/create-market/index.js

Making `augur.createMarket.getMarketFromCreateMarketReceipt` public so that users calling on-contract functions like `Universe.createBinaryMarket` directly can get the address of the market once it's created.

Making getMarketFromCreateMarketReceipt function publicly exposed

---

src/format/log/format-log-message.js
test/unit/format/log/format-log-message.js

Winning Tokens redeemed is no longer an event and the tokens transferred values being a different format than other token events is causing issues in augur node.

remove special case handling for event being used in augur node

---

src/trading/place-trade.js

`augur.trading.placeTrade` was throwing the following exception when I tried calling it via the JS console:
```
Uncaught Error: new BigNumber() not a number: undefined
at raise (bignumber.js?8748:1181)
at eval (bignumber.js?8748:1169)
at new BigNumber (bignumber.js?8748:195)
at new BigNumber (bignumber.js?8748:205)
at convertDecimalToFixedPoint (convert-decimal-to-fixed-point.js?8055:14)
at calculateTradeCost (calculate-trade-cost.js?7a38:17)
at tradeUntilAmountIsZero (trade-until-amount-is-zero.js?a628:33)
at eval (place-trade.js?466a:39)
at dispatchJsonRpcResponse (dispatch-json-rpc-response.js?4091:32)
at WebSocket.webSocketClient.onmessage (ws-transport.js?9356:26)
```
This was happening because the function `tradeUntilAmountIsZero` was looking for `p.numTicks`, which was undefined.

Add `numTicks` param to `placeTrade` function

---

scripts/dp/data/canned-markets.js

lowers the amount of ETH needed to do the scalar canned markets initial liquidity. This should hopefully save us some sweet rinkeby testnet ETH

fix canned market numbers

---

src/create-market/get-market-from-create-market-receipt.js

I noticed the `err` parameter isn't getting used, so I added a check for it.

Utilizing err parameter in callback for ethrpc.getTransactionReceipt

---

src/markets/index.js

These being here cause augur.js to fail when it is included (although it doesn't fail an tests!)

more references we need to get rid of

---

package-lock.json
package.json
scripts/dp/data/binary-order-book.json
scripts/dp/lib/cancel-order.js
scripts/dp/lib/create-order-book.js
scripts/dp/lib/create-order.js
scripts/dp/lib/fill-order.js
src/augur-node/submit-json-rpc-request.js
src/constants.js
src/markets/get-unclaimed-market-creator-fees.js
src/trading/calculate-trade-cost.js
src/trading/generate-trade-group-id.js
src/trading/get-user-trading-history.js
src/trading/index.js
src/trading/place-trade.js
src/trading/trade-until-amount-is-zero.js
test/unit/trading/place-trade.js

Resolves:
https://app.clubhouse.io/augur/story/7822/add-calculatetradecost-to-public-trading-api
https://app.clubhouse.io/augur/story/7823/reduce-number-of-shares-used-in-canned-market-orders
https://app.clubhouse.io/augur/story/7824/option-to-use-placetrade-publictrade-for-create-orders-script-instead-of-publiccreateorder
https://app.clubhouse.io/augur/story/7825/assign-trade-group-ids-to-dp-scripted-trades
https://app.clubhouse.io/augur/story/7833/improve-not-connected-to-augur-node-error
Sorry for lumping them into one big PR!  They're individually such small issues that I felt this was preferable to opening 5 tiny PRs...

7825 trade group ids

---

scripts/flash/designated-report.js
scripts/flash/dispute-contribute.js
scripts/flash/get-rep-tokens.js

since the creation of fork scripts and changes to rep-faucet. It was missed that dispute-contribute needs to pass in amount of rep. 
Changed to pull out calling rep-faucet so that we call rep-faucet only if we need rep.

pulled out calling rep faucet

---

src/reporting/claim-reporting-fees.js

All other Simplified API functions pass an error param to the callback, but since this function executes numerous transactions and returns an array of which ones failed, this PR modifies that behavior to pass a generic error to the callback.  It also renames the `errors` property to `failedTransactions` and slightly modifies the shape of its data.

Change how claimReportingFees passes errors to callback

---

package.json

grab the files from the correct docker based on augur-core version, not from :latest

removing references to :latest when copying files

---

package.json

make a shortcut for flash available outside of augur.js project. 
will facilitate running flash from augur-node or augur ui dev directories.

added flash to bin and make shortcut to 'flash' in package.json

---

scripts/run-geth-and-deploy.sh

So that after POP images are loaded we actually let geth commit to disk

Use SIGTERM to gracefully exit geth

---

src/reporting/claim-reporting-fees.js

Some minor cleanup for the onSuccess result of claimReportingFees.

Removed failed transaction contract addresses from onSuccess result

---

scripts/flash/designated-report.js
scripts/flash/get-payout-numerators.js
scripts/flash/index.js

Saw an issue where negative numbers couldn't be parsed by options parser. Added \"-10\" format to help for outcome option
Needed to trim off \" before using outcome in big number calculation.

fix issue with using negative outcomes to report

---

src/reporting/claim-reporting-fees-forked-market.js
src/reporting/claim-reporting-fees-nonforked-markets.js
test/unit/reporting/claim-reporting-fees-forked-market-initial-reporter-fork-and-redeem.js
test/unit/reporting/claim-reporting-fees-forked-market-initial-reporter-redeem.js
test/unit/reporting/claim-reporting-fees-nonforked-markets-forked-market.js
test/unit/reporting/claim-reporting-fees-nonforked-markets-no-forked-market.js

The gas estimates were previously getting returned as BigNumbers, but they should be returned as strings. Also updated misc. JSDoc info to be correct.
NOTE: This change does not cause problems for the modals that are displayed when claiming reporting fees. The UI code was already calling `.toString` on the gas estimates, and I confirmed they are still displayed as expected in the modals.

Changing gas estimates to strings for claimReportingFees functions

---

src/trading/calculate-trade-cost.js
src/utils/convert-display-amount-to-on-chain-amount.js
test/unit/trading/calculate-trade-cost.js

The only reason to do this snap is to covert human input into a nice even amount. Everywhere else we need precision.
This fixes the current issue with buying out a cat 7 order book then selling held shares
Update: On reflection I believe the snapping behavior is entirely an error and am just removing it here (confirmed the bug is still fixed in the new version). Whatever purchase from converting from display amount to on chain _should_ then appear everywhere in the UI as the originally entered display amount, so this would only fix display issues if we were incorrectly converting to display somewhere.

by default do not snap num ticks. purely a UI input nice-ity

---

src/trading/place-trade.js
test/unit/trading/place-trade.js

Passing a worse order id to placeTrade is potentially very fail prone since we may end up buying the order id we're passing. The better order id will always be a valid start point though unless someone else buys that order id first (in which case we'd fail anyway)

dont pass worse order ids to placeTrade

---

scripts/flash/get-payout-numerators.js

fix calculating payout numerators for invalid categorical 3,6,7 markets.

round down when calculating payout numerators for invalid

---

dist/augur.js
src/trading/trade-until-amount-is-zero.js
test/unit/trading/trade-until-amount-is-zero.js

Instead of just using the "loop limit" for gas estimates this will use those functions for actual trading as well.
This will solve a few issues:
- Estimates currently are lower than gas minimums hardcoded into the contracts. This causes transactions that just burn gas and ultimately do nothing. This will solve that.
- This will allow trades to pass an accurate gas estimate. Filling a single order required a 2.1 million gas limit before. Now it will cost 500-600k potentially.
- This will limit the gas used per batch of txs to fill someones complete order. Even if they really want to fill so many orders that they would use a full block we don't want to send a tx like that as miners will not pick it up. Limiting to 3 orders per tx will generally keep each tx to a reasonable limit.

Switch trading to loop limit

---

src/constants.js
src/trading/place-trade.js
src/trading/trade-until-amount-is-zero.js
test/unit/trading/place-trade.js
test/unit/trading/trade-until-amount-is-zero.js

This alters the trading logic to use hardcoded worst case gas costs for trading by market num outcomes.
We set a maximum tx gas limit and number of fills and build up the tx until we cross either amount, starting with the worst case gas cost to make an order (if applicable) and repeatedly adding the worst case gas cost to fill an order.
This means for something like a binary market just filling normal orders we'll hit the tx limit and spend ~2.5 mil gas to take 3 orders.
For an 8 categorical pathological trade (reversing positions from a short to a long) we'll hit the gas limit maximum and end up just taking 1 order and spending 2.3 - 3 mil gas.
TXs that enable creating an order add on worst case gas cost for that as well.
The constants come form new tests added to the augur-core repo …

use hardcoded estimates by outcome number and limit fills per tx

---

src/trading/trade-until-amount-is-zero.js

The "withLimit" trade functions have irregular behavior when they are prevented from actually filling orders.

always try to do at least one trade

---

scripts/flash/get-payout-numerators.js

This change is to make setting nonsensical report easier.
https://app.clubhouse.io/augur/story/14054/ui-display-for-binary-cat-markets-that-receive-nonsensical-reports

allow passing in numTick array in ###,### format

---

src/api/bind-contract-function.js

if onFailed is provided, error is not rethrown and promise gets resolved with undefined.

Fix promise behavior

---

scripts/flash/create-market-order.js
scripts/flash/fill-market-orders.js
scripts/helpers/fill-market-order.js

found issue where flash fails because outcome is a string, needs to be number.

issue where augur.js rejects outcome as string, have to parse as int.
