scripts/canned-markets.js
Five new canned markets added.
=> #1618 - Updated canned markets

.vscode/launch.json, package.json, scripts/canned-markets.js, src/constants.js, src/filters.js, src/modules/abacus.js, src/modules/connect.js, src/modules/tradingActions.js, test/integration/core/accounts.js, test/tools.js, test/unit/core/connect.js, test/unit/core/filters.js, test/unit/trading/tradingActions.js
The primary change here is an explicit check for support of subscriptions with ethrpc rather than insinuating subscription support via IPC/WS support.
=> Changes to support recent ethrpc updates.

src/contracts/generate-abi-map.js, test/unit/contracts/generate-abi-map.js
=> event signature needs arguments

src/constants.js
=> new constants to be shared between node and ui

src/markets/index.js, src/reporting/index.js, src/trading/index.js
See #184
/cc @stephensprinkle @bthaile
=> fix up module exports

index.d.ts, src/events/parse-message/parse-block-message.js, test/unit/events/parse-message/parse-block-message.js
/cc @MicahZoltu for type sanity
=> Change parse-block to emit actual block object, not just number

test/unit/events/find-event-logs-in-log-array.js
Reverts AugurProject/augur.js#200
=> Revert "indexed parameter swapped"

package-lock.json, package.json
=> change augur-contracts to prod dep

src/format/log/format-log-message.js
=> inspect as string or we lose outcome names

scripts/helpers/change-time.js, scripts/helpers/claim-proceeds.js, scripts/helpers/create-simple-order.js, scripts/helpers/create-spread-orders.js, scripts/helpers/do-initial-report.js, scripts/helpers/expiring-markets.js, scripts/helpers/fill-market-order.js, scripts/helpers/finalize-market.js, scripts/helpers/get-account-balance.js, scripts/helpers/get-initial-report.js, scripts/helpers/get-timestamp.js
created scripts for getting account balance, added setting timestamps for do-initial-report and setting timestamp to fee windows to finalize market.
pulled out getting Time contract info into own script.
added more details to listing markets.
=> Clean helper scripts

scripts/dp/index.js
=> fixed syntax error

src/markets/get-markets-created-by-user.js
Renaming this function to match the function name in augur-node.
=> Rename getMarketsCreatedByAccount to getMarketsCreatedByUser

package.json
add options parser node package for flash scripts.
=> add options parser node package

package-lock.json, scripts/dp/data/canned-markets.js, scripts/dp/lib/fill-both-order-types.js, scripts/dp/lib/fill-order.js, src/trading/calculate-trade-cost.js, src/trading/get-trade-amount-remaining.js, src/trading/place-trade.js, src/trading/simulation/simulate-buy.js, src/trading/simulation/simulate-fill-ask-order.js, src/trading/simulation/simulate-fill-bid-order.js, src/trading/simulation/simulate-sell.js, src/trading/simulation/simulate-trade.js, src/trading/trade-until-amount-is-zero.js, test/unit/trading/get-trade-amount-remaining.js, test/unit/trading/simulation/simulate-buy.js, test/unit/trading/simulation/simulate-fill-ask-order.js, test/unit/trading/simulation/simulate-fill-bid-order.js, test/unit/trading/simulation/simulate-sell.js, test/unit/trading/simulation/simulate-trade.js, test/unit/trading/trade-until-amount-is-zero.js
https://app.clubhouse.io/augur/story/4785/integration-validation-market-order-form
Also should be merged down prior to the UI PR, and the UI PR needs this version of augur.js to work. The UI will be failing tests without this augur.js verison as `sharesFilled` is never going to be returned. 
UI PR can be found here: https://github.com/AugurProject/augur/pull/1159
=> 4785 order integration

scripts/flash/push-time.js, scripts/flash/set-timestamp.js
need to parse string to number for conversion in api call to be convert to uint256 correctly.
=> issue with setting time to a specific timestamp 

scripts/dp/data/canned-markets.js, src/rpc-interface.js
Requires https://github.com/ethereumjs/ethrpc/pull/53
=> Removed ethrpc.sendEther from rpc interface

scripts/dp/index.js, scripts/flash/fork.js, scripts/flash/go-to-fork.js, scripts/flash/index.js, scripts/rep-faucet.js
added a flash script to cause a fork and modified the rep faucet to allow an amount argument and allow minting multiple times
=> Fork script

scripts/dp/data/canned-markets.js
add scalar denomination to scalar markets.
=> add _scalarDenomination to scaler markets extra info.

package.json, src/trading/trade-until-amount-is-zero.js, test/unit/trading/trade-until-amount-is-zero.js
Keeping up to date w/ the contracts
=> Update fill best order

scripts/dp/lib/approve-augur-eternal-approval-value.js, scripts/flash/approve-account.js, scripts/flash/index.js
simple script to approve an account.  pass in user address, if not then use existing env. variable for private key. I thought this would be easier to approve multiple accounts via a command line.
=> added approval flash script.

scripts/flash/fill-market-orders.js, scripts/flash/index.js, scripts/flash/list-market-orders.js
added simple script to list out orders on market. quick way to see order info. added script to fill all orders based on buy | sell and outcomeId. Mostly thinking about binary and category markets.
=> added list-market-orders 

index.d.ts
https://github.com/MikeMcl/bignumber.js/issues/143
=> Remove BN references from our index.d.ts until they fix

package.json
added nuke to augur.js. sometime just need to scorch the earth.
=> add nuke as npm command

scripts/flash/index.js
=> pass in a shorter polling interval

src/constants.js, src/reporting/claim-reporting-fees.js, src/reporting/index.js
This is a new function designed to be used by the Portfolio: Reporting page to allow users to claim all of their reporting fees by clicking a single button.
=> Adding claimReportingFees function

scripts/flash/index.js
=> add command not found and print out commands

scripts/flash/list-market-orders.js, scripts/flash/list-markets.js, src/markets/get-markets-info.js
=> change endDate to endTime in augur js [ch8647]

package.json
Seems like a good idea to me, but ¯\\\_(ツ)_/¯
=> Run geth docker scripts in foreground

src/reporting/claim-reporting-fees.js
Updating input params to more closely match what's returned by the augur-node function `getReportingFees`. Also changed from a single callback function to using `onSent`, `onFailed`, and `onSuccess`.
=> Modify input/output format for claimReportingFees function

scripts/flash/list-market-orders.js
simple goof that needs to be fixed. Getting market orders was on the first market in collection not the market the user passes in.
=> fix list market orders script, not showing correct market

scripts/flash/dispute-contribute.js
fix issue where user doesn't pass amount to use to dispute. the tx would fail because string from get-balance. decided to use large amount to dispute with.
=> fixed dispute contribute with no amount passed in.

scripts/flash/finalize-market.js, scripts/flash/index.js
finalize forking market, added flag to not move time and call finalize on market.
=> need way to finalize market for fork

package.json
5.2.6 adds support for Trezor accounts
=> ethrpc@5.2.6

README.md, package-lock.json, package.json
@pgebheim this updates the ethrpc version + fixes the MetaMask subscription issue.  Tagging you as requested, feel free to push a new augur.js version whenever you're ready!
=> Updated ethrpc version

scripts/flash/force-finalize.js
fix issue with calling finalize market from force finalize market script
=> error in passing args to finalize market

scripts/flash/escape-hatch.js
=> added help to escape hatch

scripts/flash/get-market-balance.js
update `get-market-balance`, add get winning balance for markets that are awaiting finalization or finalized.
=> Add winning balance

scripts/flash/get-market-balance.js
error in conditional statement so get-market-balance wouldn't show balance for markets in awaiting_finalization
=> fixed error in conditional stmt

scripts/flash/get-market-balance.js, scripts/flash/index.js
If market has fee window get the cash and eth balance.
=> added fee window to get balances of the fee window of the market

scripts/flash/fill-market-orders.js
Heya!
This makes sure the flash scripts walk the trades in order.
=> Walk the orders in sorted order

scripts/flash/get-balance.js
Display cash balance in `get-balance` flash script.
=> show cash balance of account

package-lock.json, scripts/dp/lib/create-order.js, src/api/bind-contract-function.js, src/constants.js, src/trading/calculate-trade-gas.js, src/trading/get-trade-amount-remaining.js, src/trading/trade-until-amount-is-zero.js, test/unit/trading/get-trade-amount-remaining.js, test/unit/trading/trade-until-amount-is-zero.js
Story details: https://app.clubhouse.io/augur/story/11003
Note: requires https://github.com/ethereumjs/ethrpc/pull/73 for the create-orders dp script to work properly.
=> Set trade gas based on the current block gas limit

src/trading/calculate-trade-gas.js
Story details: https://app.clubhouse.io/augur/story/11078
=> Round tradeUntilAmountIsZero gas

scripts/flash/market-info.js, scripts/helpers/multi-user-fork.sh
shell script to multiple users to force fork. Sneak in sorting market info properties, finally.
=> Multi user fork

scripts/helpers/multi-user-fork.sh
need to make sure this script pushes fully to fork.
=> noticed this script didn't fully push to fork, adding more rounds

scripts/flash/create-market-order.js, scripts/flash/fill-market-orders.js, scripts/flash/index.js
added new parameter to place trade for create market order and fill market orders.
=> Use shares create order

scripts/flash/list-markets.js
There has been some confusion to what address is what, added labels.
=> added labels for DR and market id

env.js, package-lock.json, scripts/decrypt-keystore.js, scripts/decrypt-keystore.sh, scripts/dp/data/canned-markets.js, scripts/flash/get-payout-numerators.js, src/rpc-interface.js
Also includes a couple minor script updates
=> Expose net namespace on ethrpc interface

scripts/flash/set-timestamp-cmd.js, scripts/flash/set-timestamp.js
not super critical but needed to add returns to quickly return instead of running through.
=> needed to have returns to finish execution

src/constants.js, src/trading/trade-until-amount-is-zero.js, test/unit/trading/trade-until-amount-is-zero.js
We can decrease cost a bit more for the case where no shares are being provided by the taker
=> only able to really modify place order cost :/

src/augur-node/connect.js
(wishing for typescript in augur.js 😬 )
=> Change of parameters for WsTransport

scripts/flash/get-payout-numerators.js
add error when numTick array length isn't correct,.
=> add error when numTick array length isn't correct

package-lock.json, package.json
important for running link'd since you don't get new version from ethrpc dep
=> speedomatic@2.1.5

scripts/full-deploy.sh
added a preflight check to make sure npm publish would work. newer git defaults to push.simple, so I explicitly set the branch.
=> Pre flight check

src/api/bind-contract-function.js, src/api/index.js, src/connect/index.js, src/get-gas-price.js, src/index.js
Eventually refactor augur.js to be a real class
```
augur.getGasPrice = (callback) => { callback(7500000000)}
```
=> Implement getGasPrice override as module-level global

scripts/flash/finalize-market.js
noticed error when trying to finalize market without pushing time.
=> method call had wrong parameters

src/augur-node/disconnect.js, src/augur-node/index.js
Story details: https://app.clubhouse.io/augur/story/17711
=> Augur.js should allow for disconnecting from augur-node, not just ethrpc

src/trading/get-user-trading-history.js
getUserTradingHistory >> getTradingHistory
=> fix getUserTradingHistory

src/index.js
bringing over changes from v2 to expose constants, needed for testability in UI.
=> to fix unit tests need to have constants a property

src/augur-node/AugurNodeHttpTransport.js
This is 60000 or 1 minute for those playing at home.
=> Increase augur node http transport to be in parity with eth transport

scripts/flash/deposit-cash-to-address.js, scripts/flash/index.js
add simple conv script to deposit cash to address, used for putting cash on fee widows.
some formatting to improve readability.
=> add flash script to deposit cash

scripts/flash/deposit-cash-to-address.js, scripts/flash/index.js
simplify to allow user to pass in flag to deposit 1 ETH on current fee window or next fee window
=> updates to deposit-cash flash script
